file-processing {
  input-dir = "input"
  output-dir = "output"
  processed-dir = "processed"
  error-dir = "error"
  chunk-size-mb = 1
}

akka {
  actor {
    provider = "cluster"
    serialization-bindings {
      "com.flo.common.CborSerializable" = jackson-cbor
    }
  }
  remote.artery {
    canonical {
      hostname = "127.0.0.1"
      port = 2551
    }
  }
  cluster {
    seed-nodes = [
      "akka://ClusterSystem@127.0.0.1:2551"
    ]

    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
  }
}